### ISSUE TITLE
contentServer.br: boolean (koa-static) mismatch type declaration

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#11]
Based on the documentation which refers that 

> ... It supports all the options of koa-static and some extra options...

`contentServer.br: true` gives an error. See photo below.

![reboost-2](https://user-images.githubusercontent.com/26875662/89288102-626b8800-d655-11ea-825e-ed62f04466ed.png)

**Comment by sarsamurmu** [comment]
`koa-static` internally uses `koa-send` to serve files. So all options mainly come from the `koa-send` package. If you see the options of `koa-send`, it has an option named `brotli` but in `koa-static` it is mistakenly stated as `br`. So please use `brotli` option instead of `br`. Anyway, thanks for reporting bugs :D
